--- #YAML:1.0
name:                CGI-Session
version:             4.40
abstract:            Persistent session data in CGI applications
license:             ~
author:              
    - Sherzod Ruzmetov <sherzodr@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    CGI:                           3.26
    Data::Dumper:                  
    Digest::MD5:                   
    Scalar::Util:                  
    Test::More:                    
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3

no_index:
    package:
    - CGI::Session::Test::SimpleObjectClass
