# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-Session
version:      4.41
version_from: lib/CGI/Session.pm
installdirs:  site
requires:
    CGI:                           3.26
    Data::Dumper:                  
    Digest::MD5:                   
    Scalar::Util:                  
    Test::More:                    

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
