--- #YAML:1.0
name:               CGI-Session
version:            4.43
abstract:           Persistent session data in CGI applications
author:
    - Sherzod Ruzmetov <sherzodr@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    CGI:           3.26
    Data::Dumper:  0
    Digest::MD5:   0
    Scalar::Util:  0
    Test::More:    0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
