# $Id: Install.pod,v 1.2 2002/08/18 22:05:52 sherzodr Exp $

=pod

=head1 NAME

Installing CGI::Session


=head1 INSTALLATION

You can download the latest release of the library either from
http://www.CPAN.org or from http://modules.ultracgis.com/dist. The library
is distributed as .tar.gz file, which is a zipped tar-ball. You can
unzip and unpack the package with the following single command (% is your shell
prompt):

    % gzip -dc CGI-Session-2.6.tar.gz | tar -xof -

It should create a folder named the same as the distribution name except the
C<.tar.gz> extension. If you have access to system's @INC folders
( usually if you are a super user in the system ) you should go with
L<standard installation|"STANDARD INSTALLATION">. Otherwise
L<custom installation|"CUSTOM INSTALLATION"> is the way to go.

=head2 STANDARD INSTALLATION

The library is installed with just like other Perl libraries, or via CPAN interactive
shell (Perl -MCPAN -e install CGI::Session).

Installation can also be done by following below instructions:

=over 4

=item 1

After downloading the distribution, C<cd> to the distribution folder

=item 2

In your shell type the following commands in the order listed:

=over 5

=item *

Perl Makefile.PL

=item *

make

=item *

make test

If the tests show positive results, type:

=item *

make install

=back

=back

=head2 CUSTOM INSTALLATION

If you do not have access to install libraries in the system folders,
you should install the library in your own private folder, somewhere in your
home directory. For this purpose, first choose/create a folder where you
want to keep your Perl libraries. I use C<perllib/> under my home folder.
Then install the library following the below steps:

=over 4

=item 1

After downloading the distribution, C<cd> to the distribution folder

=item 2

In your shell type the following commands in the order listed:

=over 5

=item *

Perl Makefile.PL INSTALLDIRS=site INSTALLSITELIB=/home/your_folder/perllib

=item *

make

=item *

make test

If the tests show positive results, type:

=item *

make install

=back

=back

Then in your Perl programs do not forget to include the following line at
the top of your code:

    use lib "/home/your_folder/perllib";

or the following a little longer alternative works as well:

    BEGIN {
        unshift @INC, "/home/your_folder/perllib";
    }

=head1 REVISION

$Revision: 1.2 $

=cut
